// all needed strings
export default {
  randomError: 'Hay un problemo.',
  name: 'Cuéntame',
  whatsYourName: '¿Cómo te llamas?',
  next: 'vale',
  yourName: 'tú nombre',
  waitingForOtherPlayers: 'Esperamos los otros jugadores.',
  connected: 'comunicado con',
  startGame: '¡vamos a jugar!',
  waitForWriter: 'Esperas el escritor',
  youAreTheWriter: 'Tu escribes',
  yourDescriptionHere: 'Tú descripción aquí',
  youDescribe: 'Describes',
  vocHelp: 'Vocabulrio',
  submit: 'vale',
  locationOnMap: 'En la mapa:',
  waitForAnswer: 'Esperamos las respuestas de los otros jugadores.',
  whereIsTheFollowingPlace: '¿Dónde esta...',
  meters: 'metros',
  yourScore: 'Tú puntos',
  reset: 'reset',
  gameRunningWantToReset: 'Otros jugadores jugan un juego. Reset?',
  roundEndMessage: 'Los puntos nuevos son:',
  nextRoundIn10s: 'Espera 10s',
  gameOver: 'Es juego es término. Los puntos son:',
  newGame: 'Juego nuevo',
  nameTaken: 'El nombre no es possible.',
  go: '¡vamos!'
}
