export default {
  randomError: 'something went wrong',
  name: 'Cuéntame',
  whatsYourName: '¿Cómo te llamas?',
  next: 'next',
  yourName: 'tú nombre',
  waitingForOtherPlayers: 'waiting for others',
  connected: 'connected',
  startGame: 'Start Game',
  waitForWriter: 'Waiting for the writer',
  youAreTheWriter: 'You are the writer',
  yourDescriptionHere: 'Your description here',
  youDescribe: 'You describe',
  vocHelp: 'Vocabulray Help',
  submit: 'submit',
  locationOnMap: 'The location on map',
  waitForAnswer: 'Waiting for other players to answer',
  whereIsTheFollowingPlace: 'Where is the following place?',
  winsThisRound: 'wins this round',
  theirDistaceWas: 'Their distace was',
  meters: 'meters',
  yourScore: 'Your score'
}
